services:

  auth-postgres:
    image: postgres:16
    container_name: relay-auth-postgres

    environment:
      POSTGRES_DB: relay_auth
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data


  auth-service:
    build:
      context: ./service/auth-service

    container_name: relay-auth-service

    ports:
      - "8000:8000"
      - "50051:50051"

    env_file:
      - ./service/auth-service/.env

    depends_on:
      - auth-postgres


  api-gateway:
    build:
      context: ./service/api-gateway

    container_name: relay-api-gateway

    ports:
      - "8001:8000"

    env_file:
      - ./service/api-gateway/.env

    depends_on:
      - auth-service


  workflow-service:
    build:
      context: ./service/workflow-service

    container_name: relay-workflow-service

    ports:
      - "8002:8000"

    depends_on:
      - auth-service


volumes:
  auth_postgres_data: