"""create human approvals

Revision ID: 5c78d157027b
Revises: ad02a814d076
Create Date: 2026-10-06 10:44:43.646961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c78d157027b'
down_revision: Union[str, Sequence[str], None] = 'ad02a814d076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('execution_step_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['execution_step_id'], ['execution_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_approvals_approver_user_id'), 'human_approvals', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_human_approvals_execution_id'), 'human_approvals', ['execution_id'], unique=False)
    op.create_index(op.f('ix_human_approvals_execution_step_id'), 'human_approvals', ['execution_step_id'], unique=False)
    op.create_index(op.f('ix_human_approvals_status'), 'human_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_human_approvals_workspace_id'), 'human_approvals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_approvals_workspace_id'), table_name='human_approvals')
    op.drop_index(op.f('ix_human_approvals_status'), table_name='human_approvals')
    op.drop_index(op.f('ix_human_approvals_execution_step_id'), table_name='human_approvals')
    op.drop_index(op.f('ix_human_approvals_execution_id'), table_name='human_approvals')
    op.drop_index(op.f('ix_human_approvals_approver_user_id'), table_name='human_approvals')
    op.drop_table('human_approvals')
    # ### end Alembic commands ###
