"""change execution step node id to string

Revision ID: d6b1897ecd18
Revises: 5c78d157027b
Create Date: 2026-10-06 11:29:21.663067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b1897ecd18'
down_revision: Union[str, Sequence[str], None] = '5c78d157027b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_steps', 'node_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_steps', 'node_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
