"""add published version to workflows

Revision ID: 093d41466667
Revises: 49bd31a2eb24
Create Date: 2026-09-26 19:09:17.133689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093d41466667'
down_revision: Union[str, Sequence[str], None] = '49bd31a2eb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('published_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'workflow_versions', ['published_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'published_version_id')
    # ### end Alembic commands ###
