"""create workflow edges table

Revision ID: 49bd31a2eb24
Revises: 9f518ad2d25d
Create Date: 2026-09-26 10:55:26.370472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bd31a2eb24'
down_revision: Union[str, Sequence[str], None] = '9f518ad2d25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.String(length=100), nullable=False),
    sa.Column('target_node_id', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edges_workflow_version_id'), 'workflow_edges', ['workflow_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_edges_workflow_version_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    # ### end Alembic commands ###
